### ISSUE TITLE
Wrong version of mariadb (causing sql-import errors)

### ISSUE THREAD

**Issue by purdy** [lando/mariadb#73]
I have a .lando.yml file that specifies a version of MariaDB that matches what I run on production (10.11). MariaDB recently added a sandbox protection line in snapshots generated by mysqldump. However, when I try to import a snap from production, I get this error:

```
ERROR at line 1: Unknown command '\-'.
```

When I log onto the database service to inspect further, the sql-import refers to mysql, which is symlinked to mariadb and its version does not match what I specified in the yml file:

```console
$ mariadb --version
mariadb  Ver 15.1 Distrib 10.5.26-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

```yml
name: mysite
recipe: lamp
config:
  webroot: web
  php: 8.1
  database: mariadb:10.11
```
